# Generated by Django 2.2.4 on 2019-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200)),
                ('client_tel', models.CharField(max_length=200)),
                ('client_mail', models.CharField(max_length=200)),
                ('client_adresse', models.CharField(max_length=200)),
            ],
        ),
    ]
