# Generated by Django 2.2.4 on 2019-08-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree_date', models.CharField(max_length=200)),
                ('entree_fournisseur', models.CharField(max_length=200)),
                ('entree_produit', models.CharField(max_length=200)),
                ('entree_quantite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FournisseurInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur_nom', models.CharField(max_length=200)),
                ('fournisseur_tel', models.CharField(max_length=200)),
                ('fournisseur_mail', models.CharField(max_length=200)),
                ('fournisseur_adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_designation', models.CharField(max_length=200)),
                ('produit_categorie', models.CharField(max_length=200)),
                ('produit_etat_stock', models.CharField(max_length=200)),
                ('produit_prix_achat', models.CharField(max_length=200)),
                ('produit_prix_vente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SortieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie_date', models.CharField(max_length=200)),
                ('sortie_fournisseur', models.CharField(max_length=200)),
                ('sortie_produit', models.CharField(max_length=200)),
                ('sortie_quantite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_nom', models.CharField(max_length=200)),
                ('utilisateur_prenom', models.CharField(max_length=200)),
                ('utilisateur_dernier_cnx', models.CharField(max_length=200)),
                ('utilisateur_mdp', models.CharField(max_length=200)),
            ],
        ),
    ]
